language: node_js
node_js:
  - node
before_install:
  - yarn
install:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: ./dist/angular-demo-vbadu
  target_branch: gh-pages
